apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-cartservice-online-boutique-service
  namespace: online-boutique-dev
  labels:
    app: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cartservice
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice:v0.10.4
        imagePullPolicy: IfNotPresent
        env:
          - name: PORT
            value: "7070"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_TRACING
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"
          - name: GCLOUD_PROJECT
            value: ""
        resources:
          limits:
            cpu: "300m"
            memory: "256Mi"
          requests:
            cpu: "150m"
            memory: "128Mi"
        ports:
          - containerPort: 7070
        livenessProbe:
          httpGet:
            path: /health
            port: 7070
          initialDelaySeconds: 15
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 7070
          initialDelaySeconds: 5
          periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: dev-cartservice-online-boutique-service
  namespace: online-boutique-dev
spec:
  type: ClusterIP
  selector:
    app: cart
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070
