apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-currencyservice-online-boutique-service
  namespace: online-boutique-dev
  labels:
    app: currency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      labels:
        app: currency
    spec:
      containers:
      - name: currencyservice
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/currencyservice:v0.10.4
        imagePullPolicy: IfNotPresent
        env:
          - name: PORT
            value: "7000"
          - name: DISABLE_PROFILER
            value: "1"
        ports:
          - containerPort: 7000
        livenessProbe:
          grpc:
            port: 7000
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          grpc:
            port: 7000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

---

apiVersion: v1
kind: Service
metadata:
  name: dev-currencyservice-online-boutique-service
  namespace: online-boutique-dev
spec:
  type: ClusterIP
  selector:
    app: currency
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
