apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-online-boutique-service
  namespace: online-boutique-dev
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/google-samples/microservices-demo/frontend:v0.8.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "productcatalog-online-boutique-service:3550"
            - name: CURRENCY_SERVICE_ADDR
              value: "currency-online-boutique-service:7000"
            - name: CART_SERVICE_ADDR
              value: "cart-online-boutique-service:7070"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "recommendation-online-boutique-service:8080"
            - name: SHIPPING_SERVICE_ADDR
              value: "shipping-online-boutique-service:50051"
            - name: CHECKOUT_SERVICE_ADDR
              value: "checkout-online-boutique-service:5050"
            - name: AD_SERVICE_ADDR
              value: "ad-online-boutique-service:9555"
            - name: EMAIL_SERVICE_ADDR
              value: "email-online-boutique-service:2500"
            - name: SHOPPING_ASSISTANT_SERVICE_ADDR
              value: "shopping-assistant-online-boutique-service:6060"
            - name: DISABLE_PROFILER
              value: "1"
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /_healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /_healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-online-boutique-service
  namespace: online-boutique-dev
spec:
  type: ClusterIP
  ports:
    - port: 222          # exposé sur le port 222
      targetPort: 8080
      protocol: TCP
  selector:
    app: frontend
