replicaCount: 1

name: productcatalogservice
image:
  repository: gcr.io/google-samples/microservices-demo/productcatalogservice
  tag: v0.4.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3550

env:
  PORT: "3550"
  DISABLE_PROFILER: "1"

resources:
  limits:
    cpu: "300m"
    memory: "256Mi"
  requests:
    cpu: "150m"
    memory: "128Mi"

livenessProbe:
  httpGet:
    path: /health
    port: 3550
  initialDelaySeconds: 10
  periodSeconds: 15

readinessProbe:
  httpGet:
    path: /health
    port: 3550
  initialDelaySeconds: 5
  periodSeconds: 10
