apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-redis-online-boutique
  namespace: online-boutique-dev
  labels:
    app: dev-redis-online-boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-redis-online-boutique
  template:
    metadata:
      labels:
        app: dev-redis-online-boutique
    spec:
      containers:
        - name: redis
          image: redis:6.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: dev-redis-online-boutique
  namespace: online-boutique-dev
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: dev-redis-online-boutique
