apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-redis
  namespace: online-boutique-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-redis
  template:
    metadata:
      labels:
        app: dev-redis
    spec:
      containers:
      - name: redis
        image: redis:6.2
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 20
          periodSeconds: 15
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          periodSeconds: 10
