apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  namespace: online-boutique-dev
spec:
  selector:
    app: recommendationservice
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
