# Currency Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: online-boutique-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
      - name: currencyservice
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/currencyservice:v0.10.4
        ports:
        - containerPort: 7000
        env:
        - name: PORT
          value: "7000"
        - name: DISABLE_PROFILER
          value: "1"
        livenessProbe:
          tcpSocket:
            port: 7000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 7000
          initialDelaySeconds: 15
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice-online-boutique-service
  namespace: online-boutique-dev
spec:
  selector:
    app: currencyservice
  ports:
  - port: 7000
    targetPort: 7000
---
# Product Catalog Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  namespace: online-boutique-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
      - name: productcatalogservice
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice:v0.10.4
        ports:
        - containerPort: 3550
        env:
        - name: PORT
          value: "3550"
        - name: DISABLE_PROFILER
          value: "1"
        livenessProbe:
          tcpSocket:
            port: 3550
          initialDelaySeconds: 15
        readinessProbe:
          tcpSocket:
            port: 3550
          initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice-online-boutique-service
  namespace: online-boutique-dev
spec:
  selector:
    app: productcatalogservice
  ports:
  - port: 3550
    targetPort: 3550
---
# Cart Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: online-boutique-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
      - name: cartservice
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice:v0.10.4
        ports:
        - containerPort: 7070
        env:
        - name: PORT
          value: "7070"
        - name: REDIS_ADDR
          value: "redis-online-boutique-service:6379"
        - name: DISABLE_PROFILER
          value: "1"
        livenessProbe:
          tcpSocket:
            port: 7070
          initialDelaySeconds: 15
        readinessProbe:
          tcpSocket:
            port: 7070
          initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice-online-boutique-service
  namespace: online-boutique-dev
spec:
  selector:
    app: cartservice
  ports:
  - port: 7070
    targetPort: 7070
---
# Recommendation Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  namespace: online-boutique-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
      - name: recommendationservice
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice:v0.10.4
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice-online-boutique-service:3550"
        - name: DISABLE_PROFILER
          value: "1"
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice-online-boutique-service
  namespace: online-boutique-dev
spec:
  selector:
    app: recommendationservice
  ports:
  - port: 8080
    targetPort: 8080
---
# Ad Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: online-boutique-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
      - name: adservice
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice:v0.10.4
        ports:
        - containerPort: 9555
        env:
        - name: PORT
          value: "9555"
        - name: DISABLE_PROFILER
          value: "1"
        livenessProbe:
          tcpSocket:
            port: 9555
          initialDelaySeconds: 20
        readinessProbe:
          tcpSocket:
            port: 9555
          initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: adservice-online-boutique-service
  namespace: online-boutique-dev
spec:
  selector:
    app: adservice
  ports:
  - port: 9555
    targetPort: 9555