# Shipping Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  namespace: online-boutique-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
      - name: shippingservice
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/shippingservice:v0.10.4
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_PROFILER
          value: "1"
        livenessProbe:
          tcpSocket:
            port: 50051
          initialDelaySeconds: 20
        readinessProbe:
          tcpSocket:
            port: 50051
          initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice-online-boutique-service
  namespace: online-boutique-dev
spec:
  selector:
    app: shippingservice
  ports:
  - port: 50051
    targetPort: 50051
---
# Checkout Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: online-boutique-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
      - name: checkoutservice
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice:v0.10.4
        ports:
        - containerPort: 5050
        env:
        - name: PORT
          value: "5050"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice-online-boutique-service:3550"
        - name: SHIPPING_SERVICE_ADDR
          value: "shippingservice-online-boutique-service:50051"
        - name: PAYMENT_SERVICE_ADDR
          value: "paymentservice-online-boutique-service:50051"
        - name: CURRENCY_SERVICE_ADDR
          value: "currencyservice-online-boutique-service:7000"
        - name: CART_SERVICE_ADDR
          value: "cartservice-online-boutique-service:7070"
        - name: EMAIL_SERVICE_ADDR
          value: "emailservice-online-boutique-service:5000"
        - name: DISABLE_PROFILER
          value: "1"
        livenessProbe:
          tcpSocket:
            port: 5050
          initialDelaySeconds: 15
        readinessProbe:
          tcpSocket:
            port: 5050
          initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice-online-boutique-service
  namespace: online-boutique-dev
spec:
  selector:
    app: checkoutservice
  ports:
  - port: 5050
    targetPort: 5050
---
# Payment Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: online-boutique-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: paymentservice
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice:v0.10.4
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_PROFILER
          value: "1"
        livenessProbe:
          tcpSocket:
            port: 50051
          initialDelaySeconds: 15
        readinessProbe:
          tcpSocket:
            port: 50051
          initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice-online-boutique-service
  namespace: online-boutique-dev
spec:
  selector:
    app: paymentservice
  ports:
  - port: 50051
    targetPort: 50051
---
# Email Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  namespace: online-boutique-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - name: emailservice
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice:v0.10.4
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: DISABLE_PROFILER
          value: "1"
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 15
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice-online-boutique-service
  namespace: online-boutique-dev
spec:
  selector:
    app: emailservice
  ports:
  - port: 5000
    targetPort: 5000