apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-productcatalogservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/monke-poggo/tld445.git
    targetRevision: main
    path: tp-k8s-esiea-2026/charts/online-boutique-service
    helm:
      valueFiles:
        - ../../helm-values/prod/productcatalogservice.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: online-boutique-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
