apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: online-boutique-dev
spec:
  selector:
    app: checkoutservice
  ports:
    - port: 5050
      targetPort: 5050
  type: ClusterIP
