apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  namespace: online-boutique-dev
spec:
  selector:
    app: paymentservice
  ports:
    - port: 50051
      targetPort: 50051
  type: ClusterIP
